services:
  branch_pgdb:
    image: postgres:15.3-alpine
    container_name: branch_pgdb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/

  branch_cs_app:
    build: .
    container_name: branch_cs_app
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_URL=${DB_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "7000:8000"
    depends_on:
      - pgdb
    command: bash -c "alembic upgrade head && python seed.py && uvicorn main:app --host 0.0.0.0"

volumes:
  branch_pgdb_data:
